server:
  port: 8080

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  #oracle 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jjang052
    password: 1234
mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml
  type-aliases-package: com.jjang051.member.dto
#mybatis 설정