spring:
  application:
    name: gallery
  devtools:
    livereload:
      enabled: true # LiveReload 활성화
    restart:
      enabled: true # 애플리케이션 자동 재시작 활성화

  #oracle 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe # Oracle DB 연결 URL
    username: dydqja01  # DB 사용자명
    password: 1234 # DB 비밀번호

