server:
  port: 8080

spring:
  application:
    name: gallery
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost
    username: jjang052
    password: 1234
  messages:
    basename:
      - messages,errors

file:
  path: C:\upload\
#mybatis:
#  config-location: classpath:mapper/config/config.xml
#  mapper-locations: classpath:mapper/sql/**/*.xml
#  # 타입 알리야스 (별칭 붙이기 >> 간편하게 쓰기 위함)
#  # config.xml 에 쓰거나 여기에 써도 됨
#  type-aliases-package: com.example.gallery.dto
