server:
  port: 8080
spring:
  application:
    name: comment

  output:
    ansi:
      enabled: always

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost
    username: jjang052
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.naver.com
    port: 465
    username: jjang051hta@naver.com
    password: asdf1234!!
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
    protocol: smtps

  # mail:
  #   host: smtp.naver.com
  #   port: 465
  #   username:
  #   password:
  #   properties:
  #     debug: true
  #     mail:
  #       smtp:
  #         auth: true
  #         ssl:
  #           enable: true
  #           trust: smtp.naver.com
  #   protocol: smtps

  # security:
  #   user:
  #     name: hong
  #     password: 1234

logging:
  level:
    org:
      hibernate:
        sql: debug
