server:
  port: 8080
spring:
  application:
    name: comment

  output:
    ansi:
      enabled: always

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost
    username: jjang052
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # security:
  #   user:
  #     name: hong
  #     password: 1234

logging:
  level:
    org:
      hibernate:
        sql: debug
